// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbHtJiMmiooi0kPHYBR7h71p6Finc-q3s',
    appId: '1:287517024269:web:55047d77698058d12bb544',
    messagingSenderId: '287517024269',
    projectId: 'gestao-ejc',
    authDomain: 'gestao-ejc.firebaseapp.com',
    storageBucket: 'gestao-ejc.appspot.com',
    measurementId: 'G-KFMT83G824',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6aGCLOzFr_hbOlcsKN52G2fUiTGZXlCg',
    appId: '1:287517024269:android:f0cecf34fe35f12a2bb544',
    messagingSenderId: '287517024269',
    projectId: 'gestao-ejc',
    storageBucket: 'gestao-ejc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeRDAGQNE_P_vWw4KjSZoNmc9ns_BscjU',
    appId: '1:287517024269:ios:1421455161bad1842bb544',
    messagingSenderId: '287517024269',
    projectId: 'gestao-ejc',
    storageBucket: 'gestao-ejc.appspot.com',
    iosBundleId: 'br.com.chagas.gestaoEjc',
  );

}